/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/end.ts" />
/// <reference path="../scenes/play.ts" />
/// <reference path="../scenes/menu.ts" /> 
//# sourceMappingURL=_reference.js.map